# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94d056b6d67502fef147a7e7c5ec4277a674d582786912fd0efd91f3082c0cbf0ac0b3979fe83e169c8fc12c43a88ef68251c4bdcfefe6280cdb2c7e5f2939be

test:
  secret_key_base: 3d1e0d65fccc17b70915a0151ea1697b2b7f036fc4645f978fa14f6ffa6e3872b3d0454e5a498d3a25ee16a26f535f68e07bf33ca0349e0edc9645dbf371dd79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
